version: '3.3'

services:
  app:
    build: './app'
    command: >
      bash -c 'yarn run start'
    environment:
      NODE_ENV: 'development'
    ports:
      - '80:3000'
      - '35729:35729'
    volumes:
      - './app:/app:rw'
      - '/app/node_modules'
